name: "Release"

permissions:
  contents: write
  actions: write

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - name: agrid-node
          - name: agrid-js-lite
          - name: agrid-js
          - name: "@agrid/core"
          - name: "@agrid/react"
          - name: "@agrid/ai"
          - name: "@agrid/nextjs-config"
          - name: "@agrid/nuxt"

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          install: false
          build: false

      - name: Get package path
        id: get-package-path
        run: |
          PACKAGE_PATH=$(pnpm list --filter=${{ matrix.package.name }} --json | jq -r '.[0].path')
          echo "path=$PACKAGE_PATH" >> "$GITHUB_OUTPUT"

      - name: Check ${{ matrix.package.name }} version and detect an update
        id: check-package-version
        uses: Agrid/check-package-version@v2.1.0
        with:
          path: ${{ steps.get-package-path.outputs.path }}

      - name: Release package ${{ matrix.package.name }}
        uses: ./.github/actions/release
        if: steps.check-package-version.outputs.is-new-version == 'true'
        with:
          package_path: ${{ steps.get-package-path.outputs.path }}
          package_name: ${{ matrix.package.name }}
          package_version: ${{ steps.check-package-version.outputs.committed-version }}
          npm_token: ${{ secrets.NPM_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Dispatch generate-references for ${{ matrix.package.name }}
        if: steps.check-package-version.outputs.is-new-version == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run generate-references.yml \
            --ref main \
            --field package_name="${{ matrix.package.name }}" \
            --field package_path="${{ steps.get-package-path.outputs.path }}"

      # Note: These upgrade workflows are for Agrid internal use
      # Comment out or remove if not needed for Agrid
      # - name: Dispatch agrid upgrade for ${{ matrix.package.name }}
      #   if: matrix.package.name == 'agrid-js' && steps.check-package-version.outputs.is-new-version == 'true'
      #   run: |
      #     curl -f -X POST \
      #          -H "Accept: application/vnd.github+json" \
      #          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
      #          https://api.github.com/repos/agridvn/agrid-js/actions/workflows/agrid-upgrade.yml/dispatches \
      #          -d '{
      #            "ref": "main",
      #            "inputs": {
      #              "package_name": "${{ matrix.package.name }}",
      #              "package_version": "${{ steps.check-package-version.outputs.committed-version }}"
      #            }
      #          }'

      # - name: Dispatch agrid.com upgrade for ${{ matrix.package.name }}
      #   if: matrix.package.name == 'agrid-js' && steps.check-package-version.outputs.is-new-version == 'true'
      #   run: |
      #     curl -f -X POST \
      #          -H "Accept: application/vnd.github+json" \
      #          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
      #          https://api.github.com/repos/agridvn/agrid-js/actions/workflows/agrid-com-upgrade.yml/dispatches \
      #          -d '{
      #            "ref": "main",
      #            "inputs": {
      #              "package_name": "${{ matrix.package.name }}",
      #              "package_version": "${{ steps.check-package-version.outputs.committed-version }}"
      #            }
      #          }'

      # Note: Agrid analytics event - comment out if not using Agrid for analytics
      # - name: Send failure event to Agrid
      #   if: ${{ failure() }}
      #   uses: Agrid/agrid-github-action@v0.1
      #   with:
      #       agrid-token: '${{ secrets.POSTHOG_API_TOKEN }}'
      #       event: 'agrid-js-github-release-workflow-failure'
      #       properties: >-
      #           {
      #             "commitSha": "${{ github.sha }}",
      #             "jobStatus": "${{ job.status }}",
      #             "commitMessage": "${{ github.event.head_commit.message }}",
      #             "commitAuthor": "${{ github.event.head_commit.author.name }}",
      #             "ref": "${{ github.ref }}",
      #             "matrixPackage": "${{ matrix.package.name }}",
      #             "packageVersion": "${{ steps.check-package-version.outputs.committed-version }}"
      #           }
